apiVersion: "v1"
kind: Pod
metadata:
  name: web1
  labels:
    service: one
    app: web
    version: v1
    role: backend
spec:
  containers:
  - name: web
    image: localhost:5000/web:latest
    command: ["/web"]
    args: []
    ports:
      - containerPort: 8080
        protocol: TCP
        hostPort: 8081
