apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /ping
spec:
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: web-pod1
          servicePort: 80
      - path: /bar
        backend:
          serviceName: web-pod2
          servicePort: 80
