apiVersion: "v1"
kind: Pod
metadata:
  name: web2
  labels:
    app: web
    version: v1
    role: backend
spec:
  containers:
  - name: web
    image: web:latest
    imagePullPolicy: Never
    command: ["/web"]
    args: []
    ports:
      - containerPort: 8080
        protocol: TCP
        hostPort: 8081
