apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: anns-role
  namespace: alices-team
subjects:
- kind: Group
  name: alice # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: reader # this must match the name of the Role
  apiGroup: rbac.authorization.k8s.io
