apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: alices-team
  name: writer
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
