apiVersion: "v1"
kind: Pod
metadata:
  name: alice
  labels:
    app: alice
    version: v5
    role: backend
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while [ \"a\" = \"a\" ]; do echo \"alice is the best\"; sleep 5; done" ]
