apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bobs-team
  name: bobs-engg
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
