apiVersion: "v1"
kind: Pod
metadata:
  name: ubuntu-pod-3
  labels:
    app: ubuntu-pod
    version: v5
    role: backend
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/bash"]
    args: ["-c", "while [ \"a\" = \"a\" ]; do echo \"Hi\"; sleep 5; done" ]
    resources:
      requests:
        cpu: 3
